export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  USER_GUIDE: '/user-guide',
  ADMIN_GUIDE: '/admin-guide',
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    COURSES: '/admin/courses',
    COURSE_EDITOR: '/admin/courses/edit/:courseId?',
    COURSE_VIEW: '/admin/courses/view/:courseId',
    USERS: '/admin/users',
    TESTS: '/admin/tests',
    REWARDS: '/admin/rewards',
    LOGS: '/admin/logs',
  },
  STUDENT: {
    COURSES: '/student/courses',
    COURSE_DETAIL: (id: number) => `/student/courses/${id}`,
    LESSON: (courseId: number, lessonId: number) => `/student/courses/${courseId}/lesson/${lessonId}`,
    TEST: (courseId: number, testId: number) => `/student/courses/${courseId}/test/${testId}`,
    PROFILE: '/student/profile',
    SETTINGS: '/student/settings',
    REWARDS: '/student/rewards',
    PROGRESS: '/student/progress',
  },
} as const;